### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by lightCraft2020** [coder-huang/sso-shiro-cas#14]
Failed to execute goal com.mycila.maven-license-plugin:maven-license-plugin:1.9.0:check (default) on project cas-server-webapp: Resource ${project.parent.basedir}/src/licensing/header.txt not found in file system, classpath or URL: no protocol: ${project.parent.basedir}/src/licensing/header.txt -> [Help 1]
[ERROR] 

这是什么原因呢？

**Comment by tinybyhuang** [comment]
@GodotGo cas-server-webapp 这是什么项目？ 看这个报错是 “maven-license-plugin”这个插件有问题

**Comment by lightCraft2020** [comment]
是的，已解决，

**Comment by lightCraft2020** [comment]
另外：sso-shiro-cas/spring-node-1/pom.xml目下的pom的190行有笔误，
sping-node-2得改成spring-node-1，不然不使用maven plugin的情况下部署到tomcat有问题。

**Comment by tinybyhuang** [comment]
@GodotGo 是的，多谢提醒
