### ISSUE TITLE
CAS登陆成功后如何控制该用户能访问哪些客户端应用

### ISSUE THREAD

**Issue by jaaazzz** [coder-huang/sso-shiro-cas#6]
你好！
请问这个项目可以实现 控制不同的用户只能访问不同客户端应用 吗？
如，用户A只有访问应用a，b的权限；用户B只有访问应用b，c的权限。
如果可以的话，是在哪配置用户对客户端应用的权限呢？
刚接触CAS。
谢谢！

**Comment by tinybyhuang** [comment]
首先数据库要存用户对应的权限，在 /src/main/java/com/spring/mybatis/realm/UserRealm.java中可以设置用户的权限到session中，然后前端JSP页面判断就可以了，其实这些应该是shiro的知识

**Comment by jaaazzz** [comment]
好的，谢谢！
